name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    
    - name: Docker meta
      id: docker_meta
      uses: go_traslator_gopher/docker_meta@v1
      with:
        images: ghrc.io/richardsplit/gopher_tr
        tag-sha: true
        tag-edge: false
        tag-latest: true
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Dcoker Buildx
      uses: docker/setup-buildx-action@v1
     # with:
       # registry: ghrc.io
       # username: ${{ github.repository_onwer}}
       # passowrd: ${{ secrets.GHRC_PASSWORD }}
    
    - name: Build image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}
        file: ./Dockerfile
