name: Docker Image CI

on:
  push:
    branches: [ docker_app ]
  pull_request:
    branches: [ docker_app ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the hello-world Docker image
      run: |
        docker build . --tag ghcr.io/richardsplit/go_translator_gopher.git#docker_app/gopher:latest
        docker run ghcr.io/richardsplit/go_translator_gopher.git#docker_app/gopher:latest
        docker push ghcr.io/richardsplit/go_translator_gopher.git#docker_app/gopher:latest
        
