name: Docker Image CI

on:
  push:
    branches: [ docker_app ]
  pull_request:
    branches: [ docker_app ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build https://github.com/richardsplit/go_translator_gopher.git#docker_app --tag gopher:$(date +%s)
    - name: docker push
