name: Build and Publish Docker Image

on:
  push:
    branches:
       - docker_app
     
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      -name: Build Docker Image
       run: docker build. --tag my-image-name:$(date +%)
       
       -name: Publish to Registry
        uses: richardsplit/go_translator_gopher@docker_app
        with: 
          name: docker_image_translator
